#!/bin/sh -x

htgettoken -v -a htvault.jlab.org -i jlab -r gluex
httokendecode -H

# As of v5.5.1, xrdcp fails to find token, so we set it
export BEARER_TOKEN_FILE=/tmp/bt_u${UID}

tmpfile=$(mktemp /tmp/gluex-xrdcp.XXXXXX)
hostname > $tmpfile
date >> $tmpfile
xrdcp -d1 -f $tmpfile roots://dtn-gluex.jlab.org//gluex/
